# Teams
teams_channel_url: "https://teams.microsoft.com/"

# Bot
bot_name: "YourBotName"

# Storage state (persist SSO session)
storage_state_file: "auth/auth_state.json"

# Force browser and install guards
force_web_client: true
install_web_guards: true

# Big waits
navigate_timeout_ms: 120000
composer_timeout_ms: 60000
banner_dismiss_timeout_ms: 6000

# Mention UX
mention_name_char_delay_ms: 35
mention_popup_wait_ms: 4000
mention_popup_poll_ms: 120

# Sending
send_button_timeout_ms: 8000
post_send_wait_ms: 600

# Bot reply polling
bot_response_timeout_ms: 130000
bot_response_poll_ms: 700

# Weird tags / code-fence defang
#   off | zwsp | space
defang_fences: "zwsp"

# Optional: try extra Chromium flags on macOS if your tenant is stubborn
# extra_args:
#   - --no-default-browser-check
#   - --disable-features=msProtocolHandlerRegistration